FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Set any ENVs
ARG NEXT_PUBLIC_ENVIRONMENT=${NEXT_PUBLIC_ENVIRONMENT}
ARG NEXT_PUBLIC_BASE_URL_PROD=${NEXT_PUBLIC_BASE_URL_PROD}
ARG NEXT_PUBLIC_BASE_URL_DEV=${NEXT_PUBLIC_BASE_URL_DEV}
ARG NEXT_PUBLIC_API_SECRET_KEY=${NEXT_PUBLIC_API_SECRET_KEY}
ARG NEXT_PUBLIC_API_SECRET_IV=${NEXT_PUBLIC_API_SECRET_IV}
ARG NEXT_PUBLIC_API_ENCRYPTION_METHOD=${NEXT_PUBLIC_API_ENCRYPTION_METHOD}

RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]