import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import '../../globals.css'
import HeaderNavigation from '../../../components/shared/HeaderNavigation'
import Footer from '../../../components/shared/Footer'
import UserProvider from '../../../provider/UserProvider'
import UserTypeNavigation from './UserTypeNavigation'
// import IsAuthenticated from '../../route/IsAuthenticated'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AutoHub Home Page',
  description: 'Generated by create next app',
}

export default function UserLayout(
{
  children,
}: {
  children: React.ReactNode
}) {
      
      const marketPlate = 
      [
        //   {
        //       name: "dashboard",
        //       url: "/user/dashboard"
        //   },
          {
              name: "My Ads",
              url: "/user/adverts"
          },
          {
              name: "Create Adverts",
              url: "/user/create-advert"
          },
      ]

      const classRoom = 
      [
          {
              name: "dashboard",
              url: "/user/dashboard"
          },
          {
              name: "course",
              url: "/user/course"
          },
          {
              name: "time-table",
              url: "/user/time-table"
          },
          {
              name: "test",
              url: "/user/test"
          },
          {
              name: "exam",
              url: "/user/exam"
          },
          {
              name: "faq",
              url: "/user/faq"
          },
      ]

      return (
        <html lang="en">
          <body 
              className={`w-12/12`}
          >
            <UserProvider>
                <HeaderNavigation />
                  {/* <UserProvider> */}
                  {/* <IsAuthenticated>                 */}
                      <div className='container relative w-full gap-5 flex justify-between mt-2 mb-4 mx-auto'
                      >
                        {  <UserTypeNavigation marketPlace={marketPlate} classRoom={classRoom} />  }
                      
                          {/* <div className='bg-green-400 d-flex bg-green-50 border-shadow drop-shadow-lg md:block h-[fit] px-1 py-5 mt-3 md:rounded-2xl -mb-24 md:mb-0'>                   */}
                          <div 
                              className='container'
                          > 
                              {children} 
                          </div>
                      </div>
                      {/* </UserProvider> */}
                    {/* </IsAuthenticated> */}
                    <div className='px-1 py-10'></div>

                <Footer />
            </UserProvider>
            
          </body>
        </html>
      )
}
