
import '../globals.css'
import Footer from "../../components/shared/Footer"
import HeaderNavigation from "../../components/shared/HeaderNavigation"

export const metadata = {
  title: 'AutoHub - Not Found',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html 
        lang="en">
      <body 
          className={`w-12/12`}
      >   
          <HeaderNavigation />
             {children}
          <Footer />
      </body>
    </html>
  )
}


