"use client"

// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import '../../globals.css'
import Link from 'next/link'
import { Toaster } from 'react-hot-toast';
import Logo from '../../../components/shared/Logo'
import { HiBookmarkSquare, HiCog6Tooth, HiEnvelope, HiHome, HiMapPin, HiMiniAdjustmentsHorizontal, HiMiniHashtag, HiMiniPencil, HiMiniPencilSquare, HiMiniPower, HiMiniShoppingCart, HiMiniUser, HiMiniUserCircle, HiMiniUsers, HiMiniViewColumns } from 'react-icons/hi2'
import { HiAcademicCap, HiBookOpen, HiOutlineTag } from 'react-icons/hi'
import { BsFillTelephoneInboundFill, BsXCircle } from 'react-icons/bs'
import { FiMenu } from 'react-icons/fi'
import { useState, useEffect } from 'react'
import clsx from 'clsx'
import { UseStore } from '../../../state/store'
import { Logout } from '../../../components/Logout'
import AdminProvider from '../../../provider/AdminProvider';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'AutoHub Home Page',
//   description: 'Generated by create next app',
// }

export default function DashboardLayout(
{
  children,
}: {
  children: React.ReactNode
}) {
      const [isMenuOpen, setMenu] = useState<boolean>(false)
      
      const Session = UseStore((state) => state)
      const token = Session.getUserToken()
      const [openLoggedOut, setOpenLoggedOut] = useState<boolean>(false)
      const [firstname, setFirstName] = useState<string>("")
      const [surname, setSurname] = useState<string>("")
      const [member, setMember] = useState<string>("") 

      useEffect(() => 
      {
         setFirstName(Session.getFName())
         setSurname(Session.getSName())
         setMember(Session.getUType())
      }, [])

      useEffect(() => 
      {
        setMenu(false)
      }, [])

      const callOpen = () => 
      {
         setMenu(true)
      }
      
      const admin = 
      [
          {
              name: "Dashboard",
              url: "/dashboard",
              icon: <HiHome className='mr-2 mt-1 text-md' />
          },
          {
              name: "Adverts",
              url: "/dashboard/adverts",
              icon: <HiMiniUserCircle className='mr-2 mt-1 text-md' />
          },
          {
              name: "Dealers",
              url: "/dashboard/dealers",
              icon: <HiMiniHashtag className='mr-2 mt-1 text-md' />
          },
          {
              name: "Members",
              url: "/dashboard/members",
              icon: <HiMiniUser className='mr-2 mt-1 text-md' />
          },
          {
              name: "Staffs",
              url: "/dashboard/staffs",
              icon: <HiMiniUser className='mr-2 mt-1 text-md' />
          },
          {
              name: "Product Entry",
              url: "/dashboard/product-entry",
              icon: <HiMiniShoppingCart className='mr-2 mt-1 text-md' />
          },
          {
              name: "Users",
              url: "/dashboard/users",
              icon: <HiMiniUsers className='mr-2 mt-1 text-md' />
          },
          {
              name: "Department",
              url: "/dashboard/department",
              icon: <HiMapPin className='mr-2 mt-1 text-md' />
          },
          {
              name: "CMS",
              url: "/dashboard/cms",
              icon: <HiMiniAdjustmentsHorizontal className='mr-2 mt-1 text-md' />
          },
          {
              name: "Plans/Packages",
              url: "/dashboard/plans",
              icon: <HiOutlineTag className='mr-2 mt-1 text-md' />
          },
          {
              name: "Test Questionaire",
              url: "/dashboard/test-questionaires",
              icon: <HiBookOpen className='mr-2 mt-1 text-md' />
          },
          {
              name: "Exam Questionaire",
              url: "/dashboard/exam-questionaires",
              icon: <HiBookOpen className='mr-2 mt-1 text-md' />
          },
          {
              name: "Students",
              url: "/dashboard/students",
              icon: <HiAcademicCap className='mr-2 mt-1 text-md' />
          },
          {
              name: "Markings",
              url: "/dashboard/markings",
              icon: <HiMiniPencil className='mr-2 mt-1 text-md' />
          },
          {
              name: "Courses",
              url: "/dashboard/courses",
              icon: <HiBookOpen className='mr-2 mt-1 text-md' />
          },
          {
              name: "Blog",
              url: "/dashboard/blog",
              icon: <HiMiniPencilSquare className='mr-2 mt-1 text-md' />
          },
          {
              name: "Modules",
              url: "/dashboard/modules",
              icon: <HiMiniViewColumns className='mr-2 mt-1 text-md' />
          },
          {
              name: "FAQS",
              url: "/dashboard/faqs",
              icon: <HiBookmarkSquare className='mr-2 mt-1 text-md' />
          },
          {
              name: "Contact Messages",
              url: "/dashboard/contact-messages",
              icon: <HiEnvelope className='mr-2 mt-1 text-md' />
          },
          {
              name: "Settings",
              url: "/dashboard/settings",
              icon: <HiCog6Tooth className='mr-2 mt-1 text-md' />
          },
      ]

      return (
        <html lang="en">
          <body 
              className={`w-12/12`}
          >
            <Toaster />
            <AdminProvider>
                <div 
                    className="relative min-h-screen md:flex"
                >                
                    <section 
                            className='md:w-0/12 w-12/12 md:hidden p-2 flex justify-between relative bg-green-800 z-5'
                    >
                        <span className='flex justify-center items-center 10/12 md:absolute z-50 md:-mt-5 mt-1'
                        >
                            <BsFillTelephoneInboundFill 
                                className='text-white w-16' 
                            />
                            <p className='text-white md:text-[14px] font-bold text-lg -ml-4 md:-mt-1'>+23409033333367</p>
                        </span>
                        <FiMenu 
                                className='text-4xl mr-1 text-white cursor-pointer md:hidden z-5' 
                                onClick={() => 
                                {
                                   setMenu(true)
                                   callOpen()
                                }}
                        />
                    </section>  
                    <div 
                        className="max-w-[1440px] mx-auto px-8 px-3 md:hidden md:p-3 z-50 -mb-2"
                    > 
                        <div className={
                            clsx("fixed z-50 w-screen lg:hidden bg-black/50 top-0 right-0 -translate-x-full duration-500", isMenuOpen && "transition ease-out duration-500 translate-x-0")
                            }
                        >
                            <div 
                                className='flex text-black left-0 top-0 z-50 w-12/12'
                            >
                                <div 
                                    className='w-8/12 pt-5 bg-green-800 border-blue-500'
                                >
                                    <span className='10/12 flex justify-end pr-5'
                                    >
                                        <BsXCircle 
                                                    className='w-10 h-10 text-white hover:text-green-300 font-bold cursor-pointer' 
                                                    onClick={() => { setMenu(false) }}
                                        />
                                    </span>
                                    {/* starts here  */}
                                    <div 
                                            className='p-3 w-full mx-auto flex justify-left items-center mb-5 ml-5 -mt-20'
                                    >
                                        <Logo />
                                    </div>
                                    <div 
                                        className='p-3 d-flex overflow-y-auto drop-shadow-xl scrollbar-thin scrollbar-thumb-indigo-300 scrollbar-track-pink-200 h-[900px] relative'
                                    >
                                        <div  
                                                className='flex justify-left h-[fit] px-10 py-5 text-white gap-3'
                                        >
                                            <div 
                                                    className='w-5/12'
                                            >
                                                <img src='' className='h-[90px] w-[90px] flex justify-left rounded-full bg-blue-200 mb-1' />                                                        
                                            </div>
                                            <div 
                                                    className='w-7/12'
                                            >                                                        
                                                <div className='w-full flex justify-left font-bold text-[15px]'>{firstname} {surname}</div>
                                                <div className='w-full flex justify-left font-bold text-md uppercase'>{member}</div>
                                                <div 
                                                    className='w-full flex justify-left font-bold text-md'
                                                >
                                                    <HiMiniPower 
                                                        className='mr-1 text-2xl mt-2 cursor-pointer hover:text-red-600' 
                                                        onClick={() => {
                                                                setOpenLoggedOut(true)                             
                                                        }}
                                                    />
                                                </div>
                                            </div>
                                        </div>
                                        <ul className='w-full'>
                                            {
                                                
                                                admin.map((user, index) => {
                                                    return (
                                                        <Link 
                                                            href={`${user?.url}`}
                                                            key={index}
                                                            onClick={() => { setMenu(false) }}
                                                        >
                                                            <li 
                                                                className='flex px-5 py-2 bg-[#1c733d] hover:bg-green-900 text-white mb-1 cursor-pointer text-left text-[14px] font-bold text-[#bdbcbb] hover:text-white'
                                                            >                                                
                                                                {user?.icon} {user?.name}
                                                            </li>
                                                        </Link>
                                                    )
                                                })
                                            }   
                                        </ul>  
                                        <div className='h-[100px]'></div>                  
                                    </div>
                                    {/* ends here  */}
                                </div>                      
                                <div 
                                    className='w-4/12 backdrop-blur-sm'                            
                                    onClick={() => {
                                        setMenu(false)
                                    }}
                                >    
                                                    
                            </div>
                            </div>
                        </div>
                    </div> 
                    {/* Medium View  */}
                    <div 
                        className="sidebar bg-green-800 text-blue-100 w-[400px] space-y-6 pt-1 pb-7 absolute inset-y-0 
                        left-0 transform -translate-x-full md:relative md:translate-x-0 transition duration-200 ease-in-out 
                        overflow-y-auto drop-shadow-xl scrollbar-thin scrollbar-thumb-indigo-300 scrollbar-track-pink-200 h-full fixed
                        "
                    >                        
                        {/* overflow-y-auto drop-shadow-xl scrollbar-thin scrollbar-thumb-indigo-300 scrollbar-track-pink-200 h-[1000px] relative */}
                        <div 
                                className='p-3 w-full mx-auto flex justify-center items-center -mb-12 -mt-3'
                        >
                            <Logo />
                        </div>
                        <div 
                                className='p-3 d-flex justify-center items-center mx-auto -mt-10'
                        >
                            <div  
                                    className='flex justify-left h-[fit] px-2 py-5 text-white gap-4'
                            >
                                <div 
                                        className='w-4/12'
                                >
                                    <img src='' className='h-[80px] w-[110px] flex justify-left rounded-full bg-blue-200 mb-3' />                                                        
                                </div>
                                <div 
                                        className='w-8/12'
                                >                                                        
                                    <div className='w-full flex justify-left font-bold text-[15px]'>{firstname} {surname}</div>
                                    <div className='w-full flex justify-left font-bold text-md uppercase'>{member}</div>
                                    <div 
                                        className='w-full flex justify-left font-bold text-md'
                                    >
                                        <HiMiniPower 
                                            className='mr-1 text-2xl mt-2 cursor-pointer hover:text-red-600' 
                                            onClick={() => {
                                                    setOpenLoggedOut(true)                             
                                            }}
                                        />
                                    </div>
                                </div>
                            </div>
                            <ul className='w-full mt-2'>
                                {
                                    
                                    admin.map((user, index) => {
                                        return (
                                            <Link 
                                                href={`${user?.url}`}
                                                key={index}
                                                shallow={true}
                                            >
                                                {/* [#bdbcbb] */}
                                                <li 
                                                    className='flex px-5 py-2 bg-[#1c733d] hover:bg-green-900 mb-1 cursor-pointer text-left text-[14px] font-bold text-white hover:text-white'
                                                >                                                
                                                    {user?.icon} {user?.name}
                                                </li>
                                            </Link>
                                        )
                                    })
                                }   
                            </ul>                    
                        </div>
                    </div>

                    { children }

                </div>
                {
                    openLoggedOut && <Logout onClick={
                                                () => {

                                                }
                                            } 
                                            deleteModal={openLoggedOut} 
                                            token={token} 
                                    />
                }
            </AdminProvider>
          </body>
        </html>
      )
}
